import type { Metadata } from "next";
import { Header } from "@/components/custom/header";
import { Background } from "@/components/custom/background";
import { Frame } from "@/components/custom/frame";
import { ThemeProvider } from "@/components/custom/theme-provider"
import { MobileMenu } from "@/components/custom/mobile-menu";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-raleway font-normal dark:bg-black bg-white">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <Header />
          <Background />
          <Frame />
          {/* <MobileMenu /> */}
          <main className="fixed z-30 h-[calc(100dvh-6.75rem)] w-[calc(100dvw-2.5rem)] left-5 top-20 md:h-[calc(100dvh-5rem)] md:w-[calc(100dvw-5rem)] md:left-10 md:top-10 overflow-y-scroll no-scrollbar">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
