import type { Metadata } from "next";
import { Header } from "@/components/custom/header";
import { Background } from "@/components/custom/background";
import { Frame } from "@/components/custom/frame";
import { ThemeProvider } from "@/components/custom/theme-provider"
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-raleway font-normal dark:bg-black bg-white">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            enableColorScheme
            disableTransitionOnChange
            >
          <Providers>
            <Header />
            <Background />
            <Frame />
            <main className="fixed left-1/2 -translate-x-1/2 z-30 top-24 md:top-10 h-[calc(100dvh-8rem)] w-[calc(100dvw-2.5rem)] md:h-[calc(100dvh-5rem)] md:w-[calc(100dvw-5rem)] container overflow-y-scroll no-scrollbar">
                {children}
            </main>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
